server:
  port: 8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://registry1:8761/eureka/,http://registry2:8761/eureka

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
spring:
  application:
    name: gateway
